[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/urkes/unq-solana-wallet/unq-wallet-keypair.json"

[programs.mainnet]
nft_candy_machine = "6U5p5noGQyx8Je33c8jp6dg3hzKKTcwuvtSEKJzK91KQ"
fair_launch = "faircnAB9k59Y4TXmLabBULeuTLgV7TkGMGNkjnA15j"
gumdrop = "gdrpGjVffourzkdDRrQmySw4aTHr8a3xmQzzxSwFD1a"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000 test/*.ts"

[workspace]
members = ["nft-candy-machine"]
